### ISSUE TITLE
Crash when trying to backup an APK

### ISSUE THREAD

**Issue by Salamandar** [machiav3lli/oandbackupx#192]
First, thanks for resurrecting this app.

But… It crashes when I try to backup an APK. Tried with different ROMs. Backup and restore data work fine.

**Comment by Tiefkuehlpizze** [comment]
Is it possible for you to look into Logcat and copy the exception and maybe a few OABX related lines before it happened? What app caused the crash?

**Comment by Salamandar** [comment]
I'm currently in the process of reinstalling my phone after a bootloop, so I'll try again and paste it here.

That was any app, I think. Both user and system.

**Comment by Salamandar** [comment]
I think that's related : 
```
11-04 10:13:05.524 11403 19812 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
11-04 10:13:05.524 11403 19812 E AndroidRuntime: Process: com.machiav3lli.backup, PID: 11403
11-04 10:13:05.524 11403 19812 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
11-04 10:13:05.524 11403 19812 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:399)
11-04 10:13:05.524 11403 19812 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
11-04 10:13:05.524 11403 19812 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
11-04 10:13:05.524 11403 19812 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
11-04 10:13:05.524 11403 19812 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
11-04 10:13:05.524 11403 19812 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-04 10:13:05.524 11403 19812 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-04 10:13:05.524 11403 19812 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
11-04 10:13:05.524 11403 19812 E AndroidRuntime: Caused by: java.lang.NullPointerException
11-04 10:13:05.524 11403 19812 E AndroidRuntime: 	at java.io.File.<init>(File.java:283)
11-04 10:13:05.524 11403 19812 E AndroidRuntime: 	at com.machiav3lli.backup.handler.action.BackupAppAction.removePackageBackup(BackupAppAction.java:283)
11-04 10:13:05.524 11403 19812 E AndroidRuntime: 	at com.machiav3lli.backup.handler.action.BackupAppAction.cleanBackup(BackupAppAction.java:87)
11-04 10:13:05.524 11403 19812 E AndroidRuntime: 	at com.machiav3lli.backup.handler.BackupRestoreHelper.backup(BackupRestoreHelper.java:57)
11-04 10:13:05.524 11403 19812 E AndroidRuntime: 	at com.machiav3lli.backup.tasks.BackupTask.doInBackground(BackupTask.java:41)
11-04 10:13:05.524 11403 19812 E AndroidRuntime: 	at com.machiav3lli.backup.tasks.BackupTask.doInBackground(BackupTask.java:29)
11-04 10:13:05.524 11403 19812 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
11-04 10:13:05.524 11403 19812 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-04 10:13:05.524 11403 19812 E AndroidRuntime: 	... 4 more
```

**Comment by Tiefkuehlpizze** [comment]
What version are you using? It looks like it's a few months old. There is a new [4.0.0 Release](https://github.com/machiav3lli/oandbackupx/releases/tag/4.0.0), but beware, it breaks compatibility with older versions.

**Comment by Salamandar** [comment]
I'm using the release in F-Droid. 3.2.0.

**Comment by Salamandar** [comment]
OK, I prefer the 4.0 UI. But please do a F-Droid stable release :)

**Comment by Tiefkuehlpizze** [comment]
Version 4.0.0 is out on [F-Droid](https://f-droid.org/en/packages/com.machiav3lli.backup/) since yesterday.

**Comment by Salamandar** [comment]
Oh, my bad !!
Well I had a crash with 4.0 while backuping an APK, but I cleared the storage of OABX and now it works. So closing.
