### ISSUE TITLE
[Bug] App crashes if exisiting backups exist.

### ISSUE THREAD

**Issue by ioogithub** [machiav3lli/oandbackupx#201]
**Description**
The app will not remember the storage location of the backups. It asks for this location every time the app is started. If a location with existing backups is selected, the app crashes.

**Steps To Reproduce**
1. Fresh start with version 4.0.0
2. Open oandbackupx
3. Select the storage location /emulated/0/oandbackupx
4. Backup some apps.
5. After successful backup close app
6. Open app, oandbackupx asks for backup location again
7. Select /emulated/0/oandbackupx
8. App crashes.
9. Open oandbackupx again, app crashes again.
10. Same result as 9
All of the above steps were repeated with a test backup to see if the backups were corrupt. Same results.

**Expected behavior**
I expect I can use the app to create and restore backups as was possible in the previous version 3.2.0.

**System Information(please complete the following information):**
 - Device: Moto G7Plus
 - Android Version: 10
 - ROM: LineageOS 17  
 - App's Version:  4.0.0 (f-droid)

** Notes **
I can only see the log file from inside the app before it crashes: "There's nothing to show!"

**Comment by heinhuiz** [comment]
I had this when I tried to trick the app to restore an app backed up with 3.x by moving the app's subfolder into the new location I set up for 4.0.0. Do you have 3.x backups in your current 4.0.0 location? That might be the cause.

**Comment by ainola** [comment]
Clean install, happens for me too. Looks like this is the culprit.

`time: 1604865057805
msg: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE flg=0x43 }
stacktrace: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE flg=0x43 }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2064)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1718)
	at android.app.Activity.startActivityForResult(Activity.java:5210)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
	at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:795)
	at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:932)
	at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1279)
	at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1267)
	at com.machiav3lli.backup.utils.PrefUtils.requireStorageLocation(PrefUtils.java:127)
	at com.machiav3lli.backup.fragments.PermissionsFragment.lambda$setupOnClicks$1$PermissionsFragment(PermissionsFragment.java:98)
	at com.machiav3lli.backup.fragments.-$$Lambda$PermissionsFragment$WTMEMF59DNctPHte7gQpFbTUkyU.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7267)
	at android.view.View.performClickInternal(View.java:7244)
	at android.view.View.access$3600(View.java:802)
	at android.view.View$PerformClick.run(View.java:27922)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
`

**Comment by ainola** [comment]
Ugh, octodroid is not easy to use. Sorry for the scrambled text. The relevant bit is

`No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE`

**Comment by machiav3lli** [comment]
@ainola wait what? You have removed the system files manager documentsUI?

**Comment by ainola** [comment]
System file manager, yes. I'm using another one instead.

I'll note that the previous version in fdroid, 3.2.0, did nothave this issue.

**Comment by machiav3lli** [comment]
@ainola for AOSP the system file manager is the only app to manage SAF(OEMs have their own instead), so, no documentsUI, no SAF.

**Comment by machiav3lli** [comment]
@ioogithub as you still didn't provide a log based on the tools I sent on TG, could you at least mention your system customizations, there could be something specific that causing this, as it's not reported by others.

**Comment by ioogithub** [comment]
> @ioogithub as you still didn't provide a log based on the tools I sent on TG,
I asked about where to find the log. Inside the app under settings-> View Log it always says:
"There's nothing to show" I didn't see other tools can you report?

> as it's not reported by others.
Are you saying that no others users are reporting this issue? I saw a discussion with others users reporting this on the TG and didn't ainola just mention they had the issue as well?

Are you not able to reproduce the issue?

I have more information, it is not happening every time any longer. It happens maybe 50% of the time. I did notice that it does happen 100% of the time after the phone is restarted, not sure if this helps as well.

**Comment by icaruseffect** [comment]
Hi I'm having the same issue and can reproduce the behaviour. I attached the logcat.

System Information(please complete the following information):

    Device: Google Pixel 3
    Android Version: 11
    ROM: Stock
    App's Version: 4.0.0 (f-droid)

```
<<< log_count = 26 >>>
[11-11 17:07:50.967 8314:8314 W/OAndBackupX.DocumentContractApi]
Failed query: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{b8a280e 8314:com.machiav3lli.backup/u0a272} (pid=8314, uid=10272) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs

[11-11 17:07:50.968 8314:8314 W/OAndBackupX.DocumentContractApi]
Failed query: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{b8a280e 8314:com.machiav3lli.backup/u0a272} (pid=8314, uid=10272) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs

[11-11 17:07:56.600 8627:8627 W/OAndBackupX.DocumentContractApi]
Failed query: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{16a4bd7 8627:com.machiav3lli.backup/u0a272} (pid=8627, uid=10272) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs

[11-11 17:07:56.680 8627:8627 W/OAndBackupX.DocumentContractApi]
Failed query: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{16a4bd7 8627:com.machiav3lli.backup/u0a272} (pid=8627, uid=10272) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs

[11-11 17:07:56.682 8627:8627 W/OAndBackupX.DocumentContractApi]
Failed query: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{16a4bd7 8627:com.machiav3lli.backup/u0a272} (pid=8627, uid=10272) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs

[11-11 17:08:45.630 8627:8627 W/OAndBackupX.DocumentContractApi]
Failed query: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{16a4bd7 8627:com.machiav3lli.backup/u0a272} (pid=8627, uid=10272) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs

[11-11 17:08:45.631 8627:8627 W/OAndBackupX.DocumentContractApi]
Failed query: java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{16a4bd7 8627:com.machiav3lli.backup/u0a272} (pid=8627, uid=10272) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs

[11-11 17:08:54.968 8627:8627 D/OAndBackupX.ShellHandler]
Running Command: toybox --version

[11-11 17:08:54.995 8627:8627 D/OAndBackupX.ShellHandler]
Command(s) '[toybox --version]' ended with 0

[11-11 17:08:54.995 8627:8627 I/OAndBackupX.ShellHandler]
Using Utilbox `toybox`: toybox 0.8.3-android

[11-11 17:08:55.009 8627:8627 D/OAndBackupX.MainActivityX]
refreshing
```

Please let me know when you need more input.

**Comment by ioogithub** [comment]
> 'll note that the previous version in fdroid, 3.2.0, did not have this issue.
I can also confirm this. This is a new issue introduced in version 4.0.0. I used the same phone and OS on the previous version 3.2.0 and never saw this problem.

**Comment by machiav3lli** [comment]
@ioogithub you're B on TG aren't you? Two days ago I wrote you three options to create the log needed still no answer.

ainola's error is caused by him/her/x deleting the system app to manage files and access permissions, if you have done the same then it's nothing something to fix on OABX side, but on yours.

3.2.0 used Java's File API which is not supported since A10 anymore without a certain hack, which is starting A11 is disabled. The move to use Android's SAF was a choice to provide all the features that 4.0.0 has over 3.2.0 and for the further development of the app and its maintainability. Further on the topic, the app follows android's development guidelines to get the access permission, but the system seems to handle it since release of A11(and update of StorageManager Apex) otherwise.

One more technical notice: Please don't wrap your answers with the quote blocks as it makes them almost unreadable/uncatchable for the human eye.

**Comment by machiav3lli** [comment]
Furthermore I'll change the issue's name to exclude the first part, as #214 is cleaner on the matter. And only your crashes will be discussed here.

**Comment by ioogithub** [comment]
> I had this when I tried to trick the app to restore an app backed up with 3.x by moving the app's subfolder into the new location I set up for 4.0.0. Do you have 3.x backups in your current 4.0.0 location? That might be the cause.

Yes I had this as well. Then I did a clean install with version 4.0.0 and I get the same issue.

**Comment by ioogithub** [comment]
I just something specific.

I opened the app, and as usual it did not remember my storage location. I selected a new storage location and the app crashed.

Then when I opened the app again I noticed that in the Settings-> User preferences->Backup folder field, the path is duplicated!

If I select it again and click save then it is not duplicated, it looks correct.

If I open the app again and look at the Backup folder, it is duplicated.

I do not think the app is saving the path correctly.

**Comment by machiav3lli** [comment]
The backup folder management is a little more complicated than you this. But I started to get the feeling that you're doing something wrong in the pick the backup folder action.

**Comment by ioogithub** [comment]
Please see the last few comments here: https://github.com/machiav3lli/oandbackupx/issues/214. Jomo and I are reporting the same issue re: the backup path is being duplicated.

There is really nothing a user can do wrong picking the folder, it is literally a 1 button selection. Many other apps use this same interface for accessing the filesystem, none of them have this crashing and losing persistence issue.

Also, the previous version worked perfectly (with this issue), this bug did not exist at all.

**Comment by Switch123456789** [comment]
I have the same issue, including the doubled path within settings.

**Comment by SysGh-st** [comment]
Just tried this app. Same issue as described.
