### ISSUE TITLE
Crashing on start up

### ISSUE THREAD

**Issue by pbanj** [machiav3lli/oandbackupx#28]
App crashes on start up on my pixel 3a running the April update. It is granted permission and allowed root. I tried the arm64 and universal versions of the newest version of the app. I'll grab a log in a bit and post it.

**Comment by machiav3lli** [comment]
Did it work out?

**Comment by pbanj** [comment]
nope and ive been busy dealing with shitheads on my discord server so i havent had time to grab the logs but i will grab them. feel free to ignore this until i post the logs

**Comment by pbanj** [comment]
`FATAL EXCEPTION: main
Process: com.machiav3lli.backup, PID: 30109
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.machiav3lli.backup/com.machiav3lli.backup.activities.IntroActivity}: java.lang.IllegalArgumentException: width and height must be > 0
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.IllegalArgumentException: width and height must be > 0
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1113)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1080)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1030)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:991)
	at com.machiav3lli.backup.handler.AppInfoHelper.getPackageInfo(AppInfoHelper.java:64)
	at com.machiav3lli.backup.activities.IntroActivity.launchMainActivity(IntroActivity.java:172)
	at com.machiav3lli.backup.activities.IntroActivity.onCreate(IntroActivity.java:77)
	at android.app.Activity.performCreate(Activity.java:7825)
	at android.app.Activity.performCreate(Activity.java:7814)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	... 11 more`

That's the log

**Comment by machiav3lli** [comment]
Seems you've an app which has <= 0 as width or height of its icon this could be get around, but could you please check if you can locate it (test app or some untrusted app) and meanwhile try to run this app https://github.com/ghmxr/apkextractor and report if you 1. get the same crash 2. see an app with no icon or with an exoticly sized icon.

**Comment by machiav3lli** [comment]
@pbanj Or even better, could you please try this [version](https://send.firefox.com/download/f654b302367c7063/#_7wvrM3as_ogREo2n5spxQ) (it has the pass >yourname<OAndBackupX) and locate the exotic app icon. Thanks

**Comment by machiav3lli** [comment]
So I think we can say it's solved. I covered such situations for the future and you catched a bad behaving App. Thanks for your cooperation.

**Comment by pbanj** [comment]
Np, thank you for fixing it.
