### ISSUE TITLE
App crashes after trying to pick backup location

### ISSUE THREAD

**Issue by szero** [machiav3lli/oandbackupx#284]
**Description**
App crashes after trying to pick location for my backup. All other dialogs asking for permissions are going through fine.

**Steps To Reproduce**

1. Click the Backup folder tab and you get "OandBackupX has stopped prompt"

**Expected behavior**
I can pick my locations folder from the file manager.manager

**Logs**
```FATAL EXCEPTION: main
Process: com.machiav3lli.backup, PID: 2730
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE flg=0xc3 }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2151)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1785)
	at android.app.Activity.startActivityForResult(Activity.java:5203)
	at s.n.b.d.startActivityForResult(Unknown Source:10)
	at s.n.b.d$a.k(:4)
	at androidx.fragment.app.Fragment.E0(:1)
	at c.onClick(java-style lambda group:15)
	at android.view.View.performClick(View.java:7161)
	at android.view.View.performClickInternal(View.java:7133)
	at android.view.View.access$3500(View.java:804)
	at android.view.View$PerformClick.run(View.java:27416)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:7604)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```
**Additional info**

I have removed some Google related apps with the help of Magisk and debloater module (didn't touch any vendor apps or system ones) and when I want to do some file operations in file manager I don't get the "Open with" dialog when I want to store something on external SD card.

**System Information(please complete the following information):**

- Device: Moto G8 Power
- Android Version: 10
- ROM: stock rom
- App's Version: 5.0.0

**Comment by tsiflimagas** [comment]
I guess you have removed the system's file manager, right?

**Comment by szero** [comment]
Ah, I guess so, I think I've only removed Files by Google app tho, will try to revert this somehow...

**Comment by tsiflimagas** [comment]
I think that even google Files app is acting like the aosp one when baked into the rom, not sure though (but it seems so). Anyway, Files app should not be removed as its role is integral in the rom, rather than just a usual file manager's. (so this goes for the google one too probably). Dirty flash your rom in order to retrieve it.

**Comment by szero** [comment]
Ok so I was able to bring system file manager back but trying to set the location brings up this error now:
```
FATAL EXCEPTION: main
Process: com.google.android.documentsui, PID: 14926
java.lang.RuntimeException: Default Root URI is not a valid root URI.
	at com.android.documentsui.base.Shared.getDefaultRootUri(Shared.java:240)
	at com.android.documentsui.AbstractActionHandler.loadHomeDir(AbstractActionHandler.java:551)
	at com.android.documentsui.picker.ActionHandler.loadDefaultLocation(ActionHandler.java:228)
	at com.android.documentsui.picker.ActionHandler.onLastAccessedStackLoaded(ActionHandler.java:188)
	at com.android.documentsui.picker.ActionHandler.lambda$x4xchQbIp2JBw1iYgZ_QB_1wH30(Unknown Source:0)
	at com.android.documentsui.picker.-$$Lambda$ActionHandler$x4xchQbIp2JBw1iYgZ_QB_1wH30.accept(Unknown Source:4)
	at com.android.documentsui.picker.LoadLastAccessedStackTask.finish(LoadLastAccessedStackTask.java:65)
	at com.android.documentsui.picker.LoadLastAccessedStackTask.finish(LoadLastAccessedStackTask.java:37)
	at com.android.documentsui.base.CheckedTask.onPostExecute(CheckedTask.java:73)
	at android.os.AsyncTask.finish(AsyncTask.java:755)
	at android.os.AsyncTask.access$900(AsyncTask.java:192)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:7604)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```

**Comment by szero** [comment]
Ok, thanks for help @tsiflimagas, this issue isn't related to OAndBackupX so I'm closing it. Will try dirty flashing  the ROM and back up from there.

**Comment by theAkito** [comment]
I removed the system file manager and run into the same issue. I removed the app, because I don't need/want it on my phone. Why does the system not ask me which app to pick to handle the operation of picking the right backup folder? This happens when you try to open pretty much any file. Is there a need to hard-code the default system manager for picking the right folder?
I use a much better file manager instead and want to use that one to pick the folder.

**Comment by machiav3lli** [comment]
@theAkito removing system's file manager renders SAF unuseable. System's files' manager is too deeply integrated into the system making such changes a system-kill. There's no good reasons to remove the file's manager nowdays. It's an old practice where smartphones still had 500MiB RAM or less.

**Comment by theAkito** [comment]
> There's no good reasons to remove the file's manager nowdays. It's an old practice where smartphones still had 500MiB RAM or less.

That's not my reason, though. I removed it because I don't want/need it and because when I search for "Files" I get 2 icons, one from my manager and one from the default one in the search results and it is hard to differentiate which one is correct.

However, I guess phones will be phones, and people have to bend and squeeze their wishes according to what The Holy Google and its products force us to do.

**Comment by landry314** [comment]
i had this same issue and it was also because i disabled "Files" because i use a better one and also was tired of seeing two apps with the same name. now it's fixed. would be nice to open the file manager we want to use but it seems too integrated.

**Comment by machiav3lli** [comment]
@landry314 for that to work with SAF, Google/Android has to allow other apps to manage SAF and that those apps implement this. This is an issue on the system side.

**Comment by scarlion1** [comment]
This's funny.  I came looking for a replacement for Titanium Backup for my new device, and the first thing I needed it for was to disable _Files_ (com.google.android.documentsui).  Now the app is crashing for the same reason. 😂

Another reason _Files_ needs to be disabled is because it doesn't respect the permissions I've set on certain directories so they are accessible.  I also have _Google Files_ installed (com.google.android.apps.nbu.files) and _X-plore_ and _Amaze_.  However, I **never** get asked which one I want to use to pick a file, even with _Files_ disabled.  In other apps, there's no problem or crashing, though, it loads some basic interface that respects permissions and I can pick the file I want.

Check the code in, for example, [PhilippC/keepass2android](https://github.com/PhilippC/keepass2android).  When this app needs me to pick a file and I have _Files_ disabled, it brings up an interface like this:
![Screenshot_20240609-133702](https://github.com/NeoApplications/Neo-Backup/assets/2446600/0768be72-cae4-4549-b333-169e38ba3f33)
