### ISSUE TITLE
[Bug] java.lang.RuntimeException: last modification time is too big

### ISSUE THREAD

**Issue by Jakeler** [machiav3lli/oandbackupx#287]
**Description**
Backing up data fails with:
`java.lang.RuntimeException: last modification time '-1229782557' is too big ( > 8589934591 ).`

**Steps To Reproduce**

1. Start a backup with data
2. Most apps work, but on a few it fails, for example: Spotify, Feedly, Network Speed Indicator
3. Fails with error popup/notification, APK is also not backed up (which works if started manually for the same apps)

**Logcat (shorted)**
```
01-19 00:18:23.249 25050 26844 D a       : [com.spotify.music] Using a class
01-19 00:18:23.249 25050 26844 I e       : Backing up: com.spotify.music [Spotify]
01-19 00:18:23.313 25050 26844 I a       : [com.spotify.music] Starting data backup
01-19 00:18:23.313 25050 26844 D a       : Running Command: toybox ls -All ..............
[...]
01-19 00:18:26.862 25050 26844 I a       : Backing up data got 991 files to backup
01-19 00:18:26.862 25050 26844 I a       : Creating data backup
01-19 00:18:26.897 25050 26844 D a       : Adding .............. to archive (filesize: 0)
[...]
01-19 00:18:28.251 25050 26844 D a       : Done compressing. Closing data.tar.gz
01-19 00:18:28.251 25050 26844 E a       : unhandledException: java.lang.RuntimeException: last modification time '-1229782557' is too big ( > 8589934591 ). (java.lang.RuntimeException occurred on data backup: java.lang.RuntimeException: last modification time '-1229782557' is too big ( > 8589934591 ).)
01-19 00:18:28.251 25050 26844 E a       : [Ljava.lang.StackTraceElement;@c0b5d8e
01-19 00:18:28.251 25050 26844 W System.err: java.lang.RuntimeException: last modification time '-1229782557' is too big ( > 8589934591 ).
01-19 00:18:28.251 25050 26844 W System.err:    at u.a.a.a.a.d.c.c(Unknown Source:49)
01-19 00:18:28.251 25050 26844 W System.err:    at u.a.a.a.a.d.c.g(:14)
01-19 00:18:28.251 25050 26844 W System.err:    at m.c.a.a.a.d0(:40)
01-19 00:18:28.251 25050 26844 W System.err:    at m.a.a.g.a.l(:22)
01-19 00:18:28.251 25050 26844 W System.err:    at m.a.a.g.a.m(:4)
01-19 00:18:28.251 25050 26844 W System.err:    at m.a.a.g.a.f(:6)
01-19 00:18:28.251 25050 26844 W System.err:    at m.a.a.g.a.n(:20)
01-19 00:18:28.251 25050 26844 W System.err:    at m.a.a.a.e.a(:16)
01-19 00:18:28.251 25050 26844 W System.err:    at m.a.a.n.a.a(:7)
01-19 00:18:28.251 25050 26844 W System.err:    at m.a.a.n.f$c.f(Unknown Source:33)
01-19 00:18:28.251 25050 26844 W System.err:    at t.k.j.a.a.i(:2)
01-19 00:18:28.251 25050 26844 W System.err:    at p.a.f0.run(:2)
01-19 00:18:28.251 25050 26844 W System.err:    at p.a.q1.a.i(Unknown Source:0)
01-19 00:18:28.251 25050 26844 W System.err:    at p.a.q1.a$a.run(:5)
01-19 00:18:28.252 25050 26844 E e       : Backup failed due to a: java.lang.RuntimeException occurred on data backup: java.lang.RuntimeException: last modification time '-1229782557' is too big ( > 8589934591 ).
01-19 00:18:28.277 25050 26844 D e       : Backup deleted: true
01-19 00:18:28.277 25050 26844 I a       : [com.spotify.music] Backup succeeded: false
```
On the other affected apps it is similar, just the time is slightly different:
```
01-19 00:30:19.046 25050 27551 I e       : Backing up: com.evozi.network [Network Speed]
01-19 00:30:49.535 25050 27551 W System.err: java.lang.RuntimeException: last modification time '-1230217179' is too big ( > 8589934591 ).
```
```
01-19 00:37:48.757 25050 27546 I e       : Backing up: com.devhd.feedly [Feedly]
01-19 00:38:04.393 25050 27551 W System.err: java.lang.RuntimeException: last modification time '-1230276951' is too big ( > 8589934591 ).
```

**System Information:**

- Device: Mi 9T
- Android Version: 10
- ROM: Havoc OS, Magisk 21.4
- App's Version: 5.0.0

**Comment by machiav3lli** [comment]
This's a new one, never reported before, but as it looks it has todo with the files having missed up last modified date.

**Comment by Jakeler** [comment]
Yes, here are indeed files with a impossible mtime, related to crashlytics:
```
davinci:/data/data/com.spotify.music # find -mtime +3650 -exec ls -l '{}' \;                                                                                                                                                                                                         
-rwx------ 1 u0_a223 u0_a223 132 1931-01-07 10:00 ./files/.Fabric/com.crashlytics.sdk.android.crashlytics-core/UUID_BeginSession.json
-rwx------ 1 u0_a223 u0_a223 15 1931-01-07 10:00 ./files/.Fabric/com.crashlytics.sdk.android.crashlytics-core/UUID_SessionOS.cls
-rwx------ 1 u0_a223 u0_a223 50 1931-01-07 10:00 ./files/.Fabric/com.crashlytics.sdk.android.crashlytics-core/UUID_SessionDevice.cls
-rwx------ 1 u0_a223 u0_a223 77 1931-01-07 10:00 ./files/.Fabric/com.crashlytics.sdk.android.crashlytics-core/UUID_BeginSession.cls
-rwx------ 1 u0_a223 u0_a223 226 1931-01-07 10:00 ./files/.Fabric/com.crashlytics.sdk.android.crashlytics-core/UUID_SessionApp.json
-rwx------ 1 u0_a223 u0_a223 204 1931-01-07 10:00 ./files/.Fabric/com.crashlytics.sdk.android.crashlytics-core/UUID_SessionDevice.json
-rwx------ 1 u0_a223 u0_a223 112 1931-01-07 10:00 ./files/.Fabric/com.crashlytics.sdk.android.crashlytics-core/UUID_SessionApp.cls
-rwx------ 1 u0_a223 u0_a223 56 1931-01-07 10:00 ./files/.Fabric/com.crashlytics.sdk.android.crashlytics-core/UUID_SessionOS.json
```
Deleting with `find -mtime +3650 -delete` does solve it and does not seam to affect the apps.
