### ISSUE TITLE
[Major Bug - app unusable] Version 6.0.0 never populates app list (infinite loading icon)

### ISSUE THREAD

**Issue by opusforlife2** [machiav3lli/oandbackupx#352]
After upgrading from version 5.1.0 to 6.0.0, I have yet to see the app list appear. The loading indicator keeps showing indefinitely, no matter how long I leave it running.

Restarting the app has no effect.

Also, I thought to try changing the backup folder to see what effect that had, but tapping on User preferences in settings causes a crash, whose log is below:

```
FATAL EXCEPTION: main
Process: com.machiav3lli.backup, PID: 29488
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at android.app.SharedPreferencesImpl.getInt(SharedPreferencesImpl.java:307)
	at androidx.preference.Preference.l(Unknown Source:18)
	at androidx.preference.SeekBarPreference.F(Unknown Source:13)
	at androidx.preference.Preference.G(Unknown Source:0)
	at androidx.preference.Preference.v(:6)
	at t.s.d.d(:30)
	at t.s.d.c(:2)
	at androidx.preference.PreferenceFragmentCompat.M0(:5)
	at com.machiav3lli.backup.fragments.PrefsUserFragment.K0(Unknown Source:3)
	at androidx.preference.PreferenceFragmentCompat.U(:3)
	at t.n.b.i0.e(:1)
	at t.n.b.i0.k(:8)
	at t.n.b.c0.E(:8)
	at t.n.b.c0.Z(Unknown Source:84)
	at t.n.b.c0.C(:4)
	at t.n.b.c0$g.run(Unknown Source:3)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

**Comment by opusforlife2** [comment]
Also, on the first boot after upgrading to 6.0.0, the app asked for the backup location, and crashed after it was selected and the app had to continue loading. Crash log:

```
FATAL EXCEPTION: main
Process: com.machiav3lli.backup, PID: 13821
java.lang.RuntimeException: Unable to resume activity {com.machiav3lli.backup/com.machiav3lli.backup.activities.IntroActivityX}: java.lang.IllegalStateException: FragmentManager is already executing transactions
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4205)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: java.lang.IllegalStateException: FragmentManager is already executing transactions
	at t.n.b.c0.B(:4)
	at t.n.b.c0.C(Unknown Source:0)
	at com.machiav3lli.backup.activities.IntroActivityX.z(:18)
	at com.machiav3lli.backup.activities.IntroActivityX.A(:2)
	at com.machiav3lli.backup.activities.IntroActivityX.B(Unknown Source:42)
	at com.machiav3lli.backup.fragments.PermissionsFragment.j0(:2)
	at t.n.b.i0.n(:4)
	at t.n.b.i0.k(:2)
	at t.n.b.c0.T(:1)
	at t.n.b.c0.w(:3)
	at t.n.b.i0.n(:7)
	at t.n.b.i0.k(:2)
	at t.n.b.c0.T(:1)
	at t.n.b.c0.w(:3)
	at t.n.b.q.onPostResume(:5)
	at t.b.c.g.onPostResume(Unknown Source:0)
	at android.app.Activity.performResume(Activity.java:7983)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
	... 11 more
```

**Comment by tsiflimagas** [comment]
There were some major changes in v6.0.0 which require users to clear app's data. Could you try it and report if the issues are fixed?

**Comment by opusforlife2** [comment]
Oh. Then it's strange that it wasn't mentioned in the release notes like it usually is. Trying now.

**Comment by opusforlife2** [comment]
@tsiflimagas Thanks. That worked. The app list shows up now, and the User preferences menu opens as well.

@machiav3lli Please add this information to the release notes so other users don't face this issue.

**Comment by machiav3lli** [comment]
@opusforlife2 yeah, went down, as it was already mentioned in the tests then.

**Comment by opusforlife2** [comment]
@machiav3lli Sorry? I didn't get that.

**Comment by machiav3lli** [comment]
It's been announcd in the respective test version in the chat group, so I forgot to include it also in the release notices.

**Comment by opusforlife2** [comment]
Alright. Please Include it in the changelog as well.
