### ISSUE TITLE
[Bug] Infinitely loads apps at startup

### ISSUE THREAD

**Issue by TMS-Namespace** [machiav3lli/oandbackupx#356]
**Description**
Just keeps loading app list at startup. 

**Steps To Reproduce**

1. Update from 5.1.0 to latest stable version. 
2. After giving all permission,  backup folder,  passwords at startup
3. Goes into infinite loop at loading aps. 

**System Information:**

- Device: Oneplus 7t 
- Android Version: 10
- ROM: OOS 10.0.15.HD65BA
- App's Version: 6.0 stable

**Comment by WaffelBit** [comment]
**Description**
as above, settings works, rest of app not useable

**Steps to Reproduce**

1. Set up app once, make some backups, set a not active schedule
2. reboot and stuff
3. try to open app again

**System Information:**

- Device: S5 mini
- Android Version: 9
- ROM: LOS 16.1Unofficial
- App Version: 6.0.0 (via f-droid)

**Logcat filtered py PID**
`--------- beginning of main
05-21 18:48:13.733  1604  1604 I Zygote  : seccomp disabled by setenforce 0
05-21 18:48:13.691  1604  1604 I main    : type=1400 audit(0.0:9811): avc: denied { write } for name="trace_marker" dev="debugfs" ino=233 scontext=u:r:zygote:s0 tcontext=u:object_r:debugfs:s0 tclass=file permissive=1
05-21 18:48:13.691  1604  1604 I main    : type=1400 audit(0.0:9811): avc: denied { open } for name="trace_marker" dev="debugfs" ino=233 scontext=u:r:zygote:s0 tcontext=u:object_r:debugfs:s0 tclass=file permissive=1
05-21 18:48:13.691  1604  1604 W main    : type=1300 audit(0.0:9811): arch=40000028 syscall=322 per=800008 success=yes exit=3 a0=ffffff9c a1=aa49b4f0 a2=20001 a3=0 items=1 ppid=2051 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 exe="/system/bin/app_process32" subj=u:r:zygote:s0 key=(null)
05-21 18:48:18.388  1604  1604 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@15451fa
05-21 18:48:18.427  1604  1623 D vndksupport: Loading /system/lib/egl/libEGL_mali.so from current namespace instead of sphal namespace.
05-21 18:48:18.546  1604  1623 D libEGL  : loaded /system/lib/egl/libEGL_mali.so
05-21 18:48:18.564  1604  1623 D vndksupport: Loading /system/lib/egl/libGLESv1_CM_mali.so from current namespace instead of sphal namespace.
05-21 18:48:18.567  1604  1623 D libEGL  : loaded /system/lib/egl/libGLESv1_CM_mali.so
05-21 18:48:18.606  1604  1604 W hiav3lli.backu: Accessing hidden method Landroid/content/res/Resources$Theme;->rebase()V (dark greylist, linking)
05-21 18:48:18.608  1604  1604 W hiav3lli.backu: Accessing hidden method Landroid/content/res/Resources$Theme;->rebase()V (dark greylist, linking)
05-21 18:48:18.631  1604  1604 W hiav3lli.backu: Accessing hidden method Landroid/content/res/Resources$Theme;->rebase()V (dark greylist, reflection)
05-21 18:48:18.637  1604  1604 I ResourcesCompat: Failed to retrieve rebase() method
05-21 18:48:18.637  1604  1604 I ResourcesCompat: java.lang.NoSuchMethodException: rebase []
05-21 18:48:18.637  1604  1604 I ResourcesCompat: 	at java.lang.Class.getMethod(Class.java:2068)
05-21 18:48:18.637  1604  1604 I ResourcesCompat: 	at java.lang.Class.getDeclaredMethod(Class.java:2047)
05-21 18:48:18.637  1604  1604 I ResourcesCompat: 	at t.b.c.j.e(:15)
05-21 18:48:18.637  1604  1604 I ResourcesCompat: 	at t.b.c.g.attachBaseContext(Unknown Source:4)
05-21 18:48:18.637  1604  1604 I ResourcesCompat: 	at m.a.a.h.a.attachBaseContext(:2)
05-21 18:48:18.637  1604  1604 I ResourcesCompat: 	at android.app.Activity.attach(Activity.java:7060)
05-21 18:48:18.637  1604  1604 I ResourcesCompat: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2911)
05-21 18:48:18.637  1604  1604 I ResourcesCompat: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
05-21 18:48:18.637  1604  1604 I ResourcesCompat: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
05-21 18:48:18.637  1604  1604 I ResourcesCompat: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
05-21 18:48:18.637  1604  1604 I ResourcesCompat: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
05-21 18:48:18.637  1604  1604 I ResourcesCompat: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
05-21 18:48:18.637  1604  1604 I ResourcesCompat: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-21 18:48:18.637  1604  1604 I ResourcesCompat: 	at android.os.Looper.loop(Looper.java:193)
05-21 18:48:18.637  1604  1604 I ResourcesCompat: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
05-21 18:48:18.637  1604  1604 I ResourcesCompat: 	at java.lang.reflect.Method.invoke(Native Method)
05-21 18:48:18.637  1604  1604 I ResourcesCompat: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
05-21 18:48:18.637  1604  1604 I ResourcesCompat: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
05-21 18:48:18.825  1604  1604 I m.c.c.a.a0.k: Provider GmsCore_OpenSSL not available
05-21 18:48:18.928  1604  1604 D OpenGLRenderer: Skia GL Pipeline
05-21 18:48:18.962  1604  1623 D vndksupport: Loading /system/lib/egl/libGLESv2_mali.so from current namespace instead of sphal namespace.
05-21 18:48:18.968  1604  1623 D libEGL  : loaded /system/lib/egl/libGLESv2_mali.so
05-21 18:48:19.239  1604  1634 I Mali    : Mali API Version : 401
05-21 18:48:19.239  1604  1634 I Mali    : Mali REVISION: Linux-r4p0-00rel0  BUILD_DATE: 2014-11-10 20:23:11 
05-21 18:48:19.250  1604  1634 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
05-21 18:48:19.251  1604  1634 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
05-21 18:48:19.251  1604  1634 I OpenGLRenderer: Initialized EGL, version 1.4
05-21 18:48:19.251  1604  1634 D OpenGLRenderer: Swap behavior 1
05-21 18:48:19.267  1604  1634 D vndksupport: Loading /vendor/lib/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
05-21 18:48:19.272  1604  1634 E ion     : ioctl c0044901 failed with code -1: Invalid argument
05-21 18:48:19.708  1604  1604 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@f34136b
05-21 18:48:20.002  1604  1604 E RootBeer: b: b() [44] - com.topjohnwu.magisk ROOT management app detected!
05-21 18:48:20.003  1604  1604 E QLog    : b: b() [44] - com.topjohnwu.magisk ROOT management app detected!
05-21 18:48:20.008  1604  1604 D IntroActivityX: Running Command: id
05-21 18:48:20.050  1604  1604 D IntroActivityX: Command(s) id ended with 0
05-21 18:48:20.256  1604  1604 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@c1f168a
05-21 18:48:20.332  1604  1604 W Chip    : Do not set the background; Chip manages its own background drawable.
05-21 18:48:20.334  1604  1604 W Chip    : Do not set the background; Chip manages its own background drawable.
05-21 18:48:20.542  1604  1604 D a       : Running Command: which toybox
05-21 18:48:20.592  1604  1604 D a       : Command(s) which toybox ended with 0
05-21 18:48:20.593  1604  1604 D a       : Running Command: "/system/bin/toybox" --version
05-21 18:48:20.638  1604  1604 D a       : Command(s) "/system/bin/toybox" --version ended with 0
05-21 18:48:20.639  1604  1604 I a       : Using Utilbox toybox : "/system/bin/toybox" : toybox 0.7.6-android
05-21 18:48:21.380  1604  1604 I Choreographer: Skipped 70 frames!  The application may be doing too much work on its main thread.
05-21 18:48:24.008  1604  1649 W hiav3lli.backu: Long monitor contention with owner DefaultDispatcher-worker-3 (1651) at android.content.res.Resources android.app.ResourcesManager.getOrCreateResources(android.os.IBinder, android.content.res.ResourcesKey, java.lang.ClassLoader)(ResourcesManager.java:753) waiters=0 in android.content.res.Resources android.app.ResourcesManager.getOrCreateResources(android.os.IBinder, android.content.res.ResourcesKey, java.lang.ClassLoader) for 139ms
05-21 18:48:27.293  1604  1615 I hiav3lli.backu: Background concurrent copying GC freed 55833(3MB) AllocSpace objects, 25(556KB) LOS objects, 63% free, 3MB/9MB, paused 313us total 232.954ms
05-21 18:48:33.690  1604  1615 I hiav3lli.backu: Background concurrent copying GC freed 57645(4MB) AllocSpace objects, 32(640KB) LOS objects, 59% free, 4MB/10MB, paused 289us total 224.916ms
05-21 18:48:33.864  1604  1615 I hiav3lli.backu: NativeAlloc concurrent copying GC freed 5956(328KB) AllocSpace objects, 0(0B) LOS objects, 59% free, 4MB/10MB, paused 269us total 161.471ms
05-21 18:48:36.077  1604  1993 W Thread  : (Null) Incomplete backup or wrong structure found in /tree/primary%3Aoandbackups/document/primary%3Aoandbackups%2FEXPORTS%2FWeekly%20Main.scheds.
05-21 18:48:36.090  1604  1994 W Thread  : (Null) Incomplete backup or wrong structure found in /tree/primary%3Aoandbackups/document/primary%3Aoandbackups%2FEXPORTS%2FWeekly%20Main.scheds.
05-21 18:48:36.151  1604  1651 I b       : EXPORTS is not installed
05-21 18:48:36.152  1604  1651 E a0      : Could not process backup folder for uninstalled application in EXPORTS: java.lang.AssertionError: Backup History is empty and package is not installed. The package is completely unknown?
05-21 18:48:36.152  1604  1649 I b       : EXPORTS is not installed
05-21 18:48:36.152  1604  1649 E a0      : Could not process backup folder for uninstalled application in EXPORTS: java.lang.AssertionError: Backup History is empty and package is not installed. The package is completely unknown?
05-21 18:48:36.158  1604  1604 D MainActivityX$a: refreshing
05-21 18:48:36.319  1604  1604 D MainActivityX$a: refreshing
05-21 18:48:36.576  1604  2007 E e$a     : unexpected: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer 
05-21 18:48:36.576  1604  2007 E e$a     : at android.app.SharedPreferencesImpl.getInt(SharedPreferencesImpl.java:302)
05-21 18:48:36.576  1604  2007 E e$a     : at m.c.a.a.a.g(:2)
05-21 18:48:36.576  1604  2007 E e$a     : at m.a.a.h.g.run(:2)
05-21 18:48:36.576  1604  2007 E e$a     : at java.lang.Thread.run(Thread.java:764)
05-21 18:48:36.694  1604  2008 E e$a     : unexpected: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer 
05-21 18:48:36.694  1604  2008 E e$a     : at android.app.SharedPreferencesImpl.getInt(SharedPreferencesImpl.java:302)
05-21 18:48:36.694  1604  2008 E e$a     : at m.c.a.a.a.g(:2)
05-21 18:48:36.694  1604  2008 E e$a     : at m.a.a.h.g.run(:2)
05-21 18:48:36.694  1604  2008 E e$a     : at java.lang.Thread.run(Thread.java:764)
`

**Comment by WaffelBit** [comment]
Ah heck.
Must've missed the changelog. sorry.
To anyone encountering this.
Reset the app data, but keep your backups, fixes it and backups are fine after.
