### ISSUE TITLE
[Bug] App crash in user prefs

### ISSUE THREAD

**Issue by abliss** [machiav3lli/oandbackupx#360]
**Description**
I upgraded from v5 to v6, and now whenever I enter User Preferences I get a crash.

**Steps To Reproduce**

1. press red settings gear
2. press User Prefrences
3. crash

**Screenshots**
Only if there's no clear logs, add screenshots to help explain your problem.

**System Information(please complete the following information):**

- Device: Cosmo Communicator
- Android Version: 9.0
- ROM: stock 
- App's Version: 6.0.0

-----------------------------
```
05-26 20:00:49.660 14588 14588 E AndroidRuntime: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
05-26 20:00:49.660 14588 14588 E AndroidRuntime:        at android.app.SharedPreferencesImpl.getInt(SharedPreferencesImpl.java:302)
05-26 20:00:49.660 14588 14588 E AndroidRuntime:        at androidx.preference.Preference.l(Unknown Source:18)
05-26 20:00:49.660 14588 14588 E AndroidRuntime:        at androidx.preference.SeekBarPreference.F(Unknown Source:13)
05-26 20:00:49.660 14588 14588 E AndroidRuntime:        at androidx.preference.Preference.G(Unknown Source:0)
05-26 20:00:49.660 14588 14588 E AndroidRuntime:        at androidx.preference.Preference.v(:6)
05-26 20:00:49.660 14588 14588 E AndroidRuntime:        at t.s.d.d(:30)
05-26 20:00:49.660 14588 14588 E AndroidRuntime:        at t.s.d.c(:2)
05-26 20:00:49.660 14588 14588 E AndroidRuntime:        at androidx.preference.PreferenceFragmentCompat.M0(:5)
05-26 20:00:49.660 14588 14588 E AndroidRuntime:        at com.machiav3lli.backup.fragments.PrefsUserFragment.K0(Unknown Source:3)
05-26 20:00:49.660 14588 14588 E AndroidRuntime:        at androidx.preference.PreferenceFragmentCompat.U(:3)
05-26 20:00:49.660 14588 14588 E AndroidRuntime:        at t.n.b.i0.e(:1)
05-26 20:00:49.660 14588 14588 E AndroidRuntime:        at t.n.b.i0.k(:8)
05-26 20:00:49.660 14588 14588 E AndroidRuntime:        at t.n.b.c0.E(:8)
05-26 20:00:49.660 14588 14588 E AndroidRuntime:        at t.n.b.c0.Z(Unknown Source:84)
05-26 20:00:49.660 14588 14588 E AndroidRuntime:        at t.n.b.c0.C(:4)
05-26 20:00:49.660 14588 14588 E AndroidRuntime:        at t.n.b.c0$g.run(Unknown Source:3)
05-26 20:00:49.660 14588 14588 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
05-26 20:00:49.660 14588 14588 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
05-26 20:00:49.660 14588 14588 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
05-26 20:00:49.660 14588 14588 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6703)
05-26 20:00:49.660 14588 14588 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-26 20:00:49.660 14588 14588 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-26 20:00:49.660 14588 14588 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
```

**Comment by abliss** [comment]
my shared_prefs.xml in caase it helps:`
```
root@localhost:/android/data/data/com.machiav3lli.backup/shared_prefs# cat com.machiav3lli.backup_preferences.xml
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <string name="languages">system</string>
    <boolean name="giveAllPermissions" value="true" />
    <boolean name="backupObbData" value="false" />
    <boolean name="biometricLock" value="false" />
    <boolean name="killBeforeAction" value="false" />
    <boolean name="backupDeviceProtectedData" value="true" />
    <boolean name="disableVerification" value="true" />
    <boolean name="acquireWakelock" value="true" />
    <string name="passwordConfirmation"></string>
    <string name="themes">system</string>
    <string name="password"></string>
    <boolean name="encryption" value="true" />
    <boolean name="enableSpecialBackups" value="false" />
    <boolean name="allowDowngrade" value="true" />
    <boolean name="excludeCache" value="true" />
    <string name="housekeepingMoment">after</string>
    <string name="oldBackups">7</string>
    <boolean name="backupExternalData" value="false" />
    <boolean name="rememberFiltering" value="true" />
    <int name="numBackupRevisions" value="2" />
</map>
```

**Comment by machiav3lli** [comment]
Just clear app's data as stated in the file CHANGELOG.md.
