### ISSUE TITLE
[Bug] Stuck while loading not ingesting installed apps

### ISSUE THREAD

**Issue by dngray** [machiav3lli/oandbackupx#372]
**Description**
Stuck while loading not ingesting installed apps

**Steps To Reproduce**

1. Open OAndBackupX
2. Set backup folder to `/storage/emulated/0/OAndBackupX/`
3. Set a password

**Expected behavior**
The apps that can be backed up should be provided in a list.

**Screenshots**
![Screenshot_20210622-225604_OAndBackupX](https://user-images.githubusercontent.com/48640805/122933514-3b49a200-d35e-11eb-8d32-6bda55d7a2f1.png)

**System Information:**

- Device: whyred  
- Android Version: 11
- ROM: (AOSP, MIUI, OOS...)  [lineage-18.1-20210621](https://download.lineageos.org/whyred)
- App's Version: 6.0.1 (FDroid)
- Magisk 23.0
-----------------------------

**Additional Notes**
I see this in logcat

```
06-22 22:53:04.942  3729  3779 I ActivityManager: Start proc 11261:com.machiav3lli.backup/u0a128 for pre-top-activity {com.machiav3lli.backup/com.machiav3lli.backup.activities.SplashActivity}
06-22 22:53:04.956  4934  4945 I adbd    : jdwp connection from 11261
06-22 22:53:04.980 11261 11261 D ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
06-22 22:53:04.982 11261 11261 W hiav3lli.backu: Insufficient pre-allocated space to mmap vdex.
06-22 22:53:04.995 11261 11261 D NetworkSecurityConfig: No Network Security Config specified, using platform default
06-22 22:53:04.996 11261 11261 D NetworkSecurityConfig: No Network Security Config specified, using platform default
06-22 22:53:04.996   721   721 E Layer   : [Surface(name=Task=336)/@0xa9544d2 - animation-leash#0] No local sync point found
06-22 22:53:04.996   721   721 E Layer   : [Surface(name=Task=336)/@0xa9544d2 - animation-leash#0] No local sync point found
06-22 22:53:04.996   721   721 E Layer   : [Surface(name=Task=1)/@0x2d75dc8 - animation-leash#0] No local sync point found
06-22 22:53:04.996   721   721 E Layer   : [Surface(name=Task=1)/@0x2d75dc8 - animation-leash#0] No local sync point found
06-22 22:53:05.000 11261 11261 D WM-WrkMgrInitializer: Initializing WorkManager with default configuration.
06-22 22:53:05.009 11261 11261 I TetheringManager: registerTetheringEventCallback:com.machiav3lli.backup
06-22 22:53:05.069   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:05.178   607   607 I chatty  : uid=9999(nobody) keymaster@3.0-s identical 10 lines
06-22 22:53:05.178   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:05.190 11261 11261 I c.c.c.a.a0.k: Provider GmsCore_OpenSSL not available
06-22 22:53:05.252 11261 11285 I AdrenoGLES: QUALCOMM build                   : f2ab992, I401605978b
06-22 22:53:05.252 11261 11285 I AdrenoGLES: Build Date                       : 09/28/19
06-22 22:53:05.252 11261 11285 I AdrenoGLES: OpenGL ES Shader Compiler Version: EV031.27.05.01
06-22 22:53:05.252 11261 11285 I AdrenoGLES: Local Branch                     :
06-22 22:53:05.252 11261 11285 I AdrenoGLES: Remote Branch                    :
06-22 22:53:05.252 11261 11285 I AdrenoGLES: Remote Branch                    :
06-22 22:53:05.252 11261 11285 I AdrenoGLES: Reconstruct Branch               :
06-22 22:53:05.252 11261 11285 I AdrenoGLES: Build Config                     : S L 8.0.11 AArch64
06-22 22:53:05.256 11261 11285 I AdrenoGLES: PFP: 0x005ff11a, ME: 0x005ff066
06-22 22:53:05.272   571   571 I hwservicemanager: getTransport: Cannot find entry android.hardware.graphics.mapper@4.0::IMapper/default in either framework or device manifest.
06-22 22:53:05.272 11261 11285 I Gralloc4: mapper 4.x is not supported
06-22 22:53:05.272   571   571 I hwservicemanager: getTransport: Cannot find entry android.hardware.graphics.mapper@3.0::IMapper/default in either framework or device manifest.
06-22 22:53:05.272 11261 11285 W Gralloc3: mapper 3.x is not supported
06-22 22:53:05.288  3729  3776 W system_server: Insufficient pre-allocated space to mmap vdex.
06-22 22:53:05.292  3729  3776 I ActivityTaskManager: Displayed com.machiav3lli.backup/.activities.SplashActivity: +370ms
06-22 22:53:05.303   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:05.326   607   607 I chatty  : uid=9999(nobody) keymaster@3.0-s identical 2 lines
06-22 22:53:05.326   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:05.333 11298 11298 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
06-22 22:53:05.338 11298 11298 I AndroidRuntime: Using default boot image
06-22 22:53:05.339 11298 11298 I AndroidRuntime: Leaving lock profiling enabled
06-22 22:53:05.343 11298 11298 I app_process: Core platform API reporting enabled, enforcing=false
06-22 22:53:05.347   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:05.446   607   607 I chatty  : uid=9999(nobody) keymaster@3.0-s identical 8 lines
06-22 22:53:05.446   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:05.465 11298 11298 D app_process: Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
06-22 22:53:05.465 11298 11298 D app_process: I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt66l.dat
06-22 22:53:05.469   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:05.469   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:05.478 11298 11298 I app_process: The ClassLoaderContext is a special shared library.
06-22 22:53:05.489   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:05.489   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:05.501 11298 11298 W app_process: JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
06-22 22:53:05.509   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:05.509   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:05.510 11298 11298 D AndroidRuntime: Calling main entry com.android.commands.content.Content
06-22 22:53:05.527 11298 11298 D AndroidRuntime: Shutting down VM
06-22 22:53:05.530   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:05.572  3729  4323 I ActivityTaskManager: START u0 {cmp=com.machiav3lli.backup/.activities.IntroActivityX (has extras)} from uid 10128
06-22 22:53:05.549   607   607 I chatty  : uid=9999(nobody) keymaster@3.0-s identical 2 lines
06-22 22:53:05.549   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:05.575   699   699 I android.hardware.power-service-qti: Power setMode: 5 to: 1
06-22 22:53:05.586  3729  4323 W ActivityTaskManager: Tried to set launchTime (0) < mLastActivityLaunchTime (2278454)
06-22 22:53:05.655   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:05.779  3729  4323 D BiometricService: canAuthenticate: User=0, Caller=0, Authenticators=255
06-22 22:53:05.779  3729  4323 D BiometricService: Package: com.machiav3lli.backup Authenticator ID: 0 Modality: 2 Reported Modality: 2 Status: 6
06-22 22:53:05.779  3729  4323 D AuthService: canAuthenticate, userId: 0, callingUserId: 0, authenticators: 255, result: 11
06-22 22:53:05.783  3729  4323 I ActivityTaskManager: START u0 {cmp=com.machiav3lli.backup/.activities.MainActivityX} from uid 10128
06-22 22:53:05.763   607   607 I chatty  : uid=9999(nobody) keymaster@3.0-s identical 10 lines
06-22 22:53:05.763   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:05.785   699   699 I android.hardware.power-service-qti: Power setMode: 5 to: 1
06-22 22:53:05.795 11261 11261 E RootBeer: b: b() [44] - com.topjohnwu.magisk ROOT management app detected!
06-22 22:53:05.795 11261 11261 E QLog    : b: b() [44] - com.topjohnwu.magisk ROOT management app detected!
06-22 22:53:05.797 11261 11261 D IntroActivityX: Running Command: id
06-22 22:53:05.809 11261 11261 D IntroActivityX: Command(s) id ended with 0
06-22 22:53:05.877  3729  4323 W ActivityTaskManager: Tried to set launchTime (0) < mLastActivityLaunchTime (2279073)
06-22 22:53:05.936 11261 11261 W Chip    : Do not set the background; Chip manages its own background drawable.
06-22 22:53:05.963     0     0 I init    : Untracked pid 11297 exited with status 0
06-22 22:53:05.937 11261 11261 W Chip    : Do not set the background; Chip manages its own background drawable.
06-22 22:53:06.003   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:06.111   607   607 I chatty  : uid=9999(nobody) keymaster@3.0-s identical 10 lines
06-22 22:53:06.111   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:06.127 11261 11261 D a       : Running Command: which toybox
06-22 22:53:06.139 11261 11261 D a       : Command(s) which toybox ended with 0
06-22 22:53:06.139 11261 11261 D a       : Running Command: "/system/bin/toybox" --version
06-22 22:53:06.150 11261 11261 D a       : Command(s) "/system/bin/toybox" --version ended with 0
06-22 22:53:06.150 11261 11261 I a       : Using Utilbox toybox : "/system/bin/toybox" : toybox 0.8.3-android
06-22 22:53:06.160   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:06.614   607   607 I chatty  : uid=9999(nobody) keymaster@3.0-s identical 46 lines
06-22 22:53:06.614   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:06.637 11261 11261 I Choreographer: Skipped 38 frames!  The application may be doing too much work on its main thread.
06-22 22:53:06.753 11261 11285 I OpenGLRenderer: Davey! duration=756ms; Flags=1, IntendedVsync=2279481654902, Vsync=2280114988210, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=2280123816774, AnimationStart=2280123818806, PerformTraversalsStart=2280123955941, DrawStart=2280217987253, SyncQueued=2280226212201, SyncStart=2280226970014, IssueDrawCommandsStart=2280227199597, SwapBuffers=2280238268348, FrameCompleted=2280239351213, DequeueBufferDuration=170261, QueueBufferDuration=344271, GpuCompleted=25,
06-22 22:53:06.762  3729  3776 I ActivityTaskManager: Displayed com.machiav3lli.backup/.activities.MainActivityX: +1s185ms
06-22 22:53:07.064   699   699 I android.hardware.power-service-qti: Power setMode: 5 to: 0
06-22 22:53:07.538  3729  5117 W NotificationService: Toast already killed. pkg=com.topjohnwu.magisk token=android.os.BinderProxy@9560a32
06-22 22:53:08.259  6082  6082 W im.vector.app: type=1400 audit(0.0:397): avc: denied { search } for name="/" dev="cgroup2" ino=1 scontext=u:r:untrusted_app:s0:c138,c256,c512,c768 tcontext=u:object_r:cgroup_bpf:s0 tclass=dir permissive=0 app=im.vector.app
06-22 22:53:09.038  3729  3765 W WindowManager: Unable to start animation, surface is null or no children.
06-22 22:53:08.259  6082  6082 W im.vector.app: type=1400 audit(0.0:398): avc: denied { search } for name="/" dev="cgroup2" ino=1 scontext=u:r:untrusted_app:s0:c138,c256,c512,c768 tcontext=u:object_r:cgroup_bpf:s0 tclass=dir permissive=0 app=im.vector.app
06-22 22:53:12.266 11261 11261 D s       : refreshing
06-22 22:53:12.294   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:12.497   607   607 I chatty  : uid=9999(nobody) keymaster@3.0-s identical 10 lines
06-22 22:53:12.498   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:12.535 11261 11261 D s       : refreshing
06-22 22:53:12.553   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:12.553   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:12.553  3729  3802 E LightsService: Light requested not available on this device. 2
06-22 22:53:12.577   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:12.894   607   607 I chatty  : uid=9999(nobody) keymaster@3.0-s identical 20 lines
06-22 22:53:12.894   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:12.925 11261 11793 E f$a     : unexpected: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
06-22 22:53:12.925 11261 11793 E f$a     : at android.app.SharedPreferencesImpl.getInt(SharedPreferencesImpl.java:321)
06-22 22:53:12.925 11261 11793 E f$a     : at c.c.a.a.a.i(:2)
06-22 22:53:12.925 11261 11793 E f$a     : at c.a.a.h.l.run(:4)
06-22 22:53:12.925 11261 11793 E f$a     : at java.lang.Thread.run(Thread.java:923)
06-22 22:53:12.930   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:12.991   607   607 I chatty  : uid=9999(nobody) keymaster@3.0-s identical 4 lines
06-22 22:53:12.991   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:13.022 11261 11275 I hiav3lli.backu: Background concurrent copying GC freed 85167(3466KB) AllocSpace objects, 37(2516KB) LOS objects, 81% free, 5474KB/29MB, paused 188us total 139.755ms
06-22 22:53:13.028   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:13.098   607   607 I chatty  : uid=9999(nobody) keymaster@3.0-s identical 4 lines
06-22 22:53:13.098   607   607 W android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
06-22 22:53:13.131 11261 11794 E f$a     : unexpected: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
06-22 22:53:13.131 11261 11794 E f$a     : at android.app.SharedPreferencesImpl.getInt(SharedPreferencesImpl.java:321)
06-22 22:53:13.131 11261 11794 E f$a     : at c.c.a.a.a.i(:2)
06-22 22:53:13.131 11261 11794 E f$a     : at c.a.a.h.l.run(:4)
06-22 22:53:13.131 11261 11794 E f$a     : at java.lang.Thread.run(Thread.java:923)
```

**Comment by dngray** [comment]
Hmm, i can't seem to reproduce this now. I cleared the app and didn't set a password and it went in straight away... cleared app settings again and set password after it prompted to do so "Lets Go..." and it still seems to work. hmm.

**Comment by machiav3lli** [comment]
As mentioned in the changelog, updating to 6.0.x, you should clean up the data.
