### ISSUE TITLE
[Bug] Crashed during app backup

### ISSUE THREAD

**Issue by opusforlife2** [machiav3lli/oandbackupx#798]
**Description**

This might be a one-off error. While an app's backup was going on, Neo Backup crashed. However, the backup seemed to have been completed nevertheless.

Crash log:

```
FATAL EXCEPTION: main
Process: com.machiav3lli.backup, PID: 8018
java.lang.IllegalStateException: item can't be saved
	at androidx.compose.runtime.saveable.SaveableStateRegistryImpl.performSave(Unknown Source:86)
	at androidx.compose.runtime.saveable.SaverKt$AutoSaver$1.invoke(SourceFile:49)
	at androidx.compose.runtime.saveable.SaveableHolder.invoke(Unknown Source:8)
	at androidx.compose.runtime.saveable.SaveableStateRegistryImpl.performSave(Unknown Source:56)
	at androidx.compose.foundation.lazy.layout.LazySaveableStateHolder.performSave(Unknown Source:32)
	at androidx.compose.foundation.ScrollState$Companion$Saver$1.invoke(SourceFile:29)
	at androidx.compose.runtime.saveable.SaveableHolder.invoke(Unknown Source:8)
	at androidx.compose.runtime.saveable.SaveableStateRegistryImpl.performSave(Unknown Source:56)
	at androidx.compose.runtime.saveable.SaverKt$AutoSaver$1.invoke(SourceFile:49)
	at androidx.compose.runtime.saveable.SaveableHolder.invoke(Unknown Source:8)
	at androidx.compose.runtime.saveable.SaveableStateRegistryImpl.performSave(Unknown Source:56)
	at androidx.activity.ComponentActivity$$ExternalSyntheticLambda1.saveState(Unknown Source:88)
	at androidx.savedstate.SavedStateRegistryController.performSave(Unknown Source:63)
	at androidx.activity.ComponentActivity.onSaveInstanceState(Unknown Source:16)
	at android.app.Activity.performSaveInstanceState(Activity.java:2203)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1520)
	at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:5830)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5229)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5195)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5260)
	at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:43)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**System Information:**

- Device: Xiaomi Mi 5
- Android Version: 12
- ROM: LOS 19.1
- App's Version: 8.3.3

**Comment by machiav3lli** [comment]
This is possibly related to a bug fixed in 8.3.4, please check and report back (depends on when F-Droid do the build)
